package com.jiahan.action.Dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.jiahan.action.Dao.Book;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK".
*/
public class BookDao extends AbstractDao<Book, Long> {

    public static final String TABLENAME = "BOOK";

    /**
     * Properties of entity Book.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BookName = new Property(1, String.class, "bookName", false, "BOOK_NAME");
        public final static Property Author = new Property(2, String.class, "author", false, "AUTHOR");
        public final static Property Language = new Property(3, String.class, "language", false, "LANGUAGE");
        public final static Property Introduction = new Property(4, String.class, "introduction", false, "INTRODUCTION");
        public final static Property AddTime = new Property(5, String.class, "addTime", false, "ADD_TIME");
        public final static Property Type = new Property(6, Integer.class, "type", false, "TYPE");
        public final static Property Plane = new Property(7, String.class, "plane", false, "PLANE");
        public final static Property ReadProgress = new Property(8, Integer.class, "readProgress", false, "READ_PROGRESS");
        public final static Property Tag = new Property(9, Integer.class, "tag", false, "TAG");
        public final static Property Finish = new Property(10, String.class, "finish", false, "FINISH");
    };


    public BookDao(DaoConfig config) {
        super(config);
    }
    
    public BookDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"BOOK_NAME\" TEXT NOT NULL ," + // 1: bookName
                "\"AUTHOR\" TEXT," + // 2: author
                "\"LANGUAGE\" TEXT," + // 3: language
                "\"INTRODUCTION\" TEXT," + // 4: introduction
                "\"ADD_TIME\" TEXT," + // 5: addTime
                "\"TYPE\" INTEGER," + // 6: type
                "\"PLANE\" TEXT," + // 7: plane
                "\"READ_PROGRESS\" INTEGER," + // 8: readProgress
                "\"TAG\" INTEGER," + // 9: tag
                "\"FINISH\" TEXT);"); // 10: finish
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Book entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getBookName());
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(3, author);
        }
 
        String language = entity.getLanguage();
        if (language != null) {
            stmt.bindString(4, language);
        }
 
        String introduction = entity.getIntroduction();
        if (introduction != null) {
            stmt.bindString(5, introduction);
        }
 
        String addTime = entity.getAddTime();
        if (addTime != null) {
            stmt.bindString(6, addTime);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(7, type);
        }
 
        String plane = entity.getPlane();
        if (plane != null) {
            stmt.bindString(8, plane);
        }
 
        Integer readProgress = entity.getReadProgress();
        if (readProgress != null) {
            stmt.bindLong(9, readProgress);
        }
 
        Integer tag = entity.getTag();
        if (tag != null) {
            stmt.bindLong(10, tag);
        }
 
        String finish = entity.getFinish();
        if (finish != null) {
            stmt.bindString(11, finish);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Book readEntity(Cursor cursor, int offset) {
        Book entity = new Book( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // bookName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // author
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // language
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // introduction
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // addTime
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // type
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // plane
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // readProgress
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // tag
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // finish
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Book entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBookName(cursor.getString(offset + 1));
        entity.setAuthor(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLanguage(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIntroduction(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAddTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setType(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setPlane(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setReadProgress(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setTag(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setFinish(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Book entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Book entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
