package com.jiahan.action.Dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK".
*/
public class BookDao extends AbstractDao<Book, Long> {

    public static final String TABLENAME = "BOOK";

    /**
     * Properties of entity Book.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BookName = new Property(1, String.class, "bookName", false, "BOOK_NAME");
        public final static Property AddTime = new Property(2, String.class, "addTime", false, "ADD_TIME");
        public final static Property Introduction = new Property(3, String.class, "introduction", false, "INTRODUCTION");
        public final static Property BeginTime = new Property(4, String.class, "beginTime", false, "BEGIN_TIME");
        public final static Property EndTime = new Property(5, String.class, "endTime", false, "END_TIME");
        public final static Property Plan = new Property(6, String.class, "plan", false, "PLAN");
        public final static Property Summary = new Property(7, String.class, "summary", false, "SUMMARY");
        public final static Property ReadProgress = new Property(8, Integer.class, "readProgress", false, "READ_PROGRESS");
        public final static Property Author = new Property(9, String.class, "author", false, "AUTHOR");
        public final static Property Tag = new Property(10, String.class, "tag", false, "TAG");
    };


    public BookDao(DaoConfig config) {
        super(config);
    }
    
    public BookDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"BOOK_NAME\" TEXT NOT NULL ," + // 1: bookName
                "\"ADD_TIME\" TEXT," + // 2: addTime
                "\"INTRODUCTION\" TEXT," + // 3: introduction
                "\"BEGIN_TIME\" TEXT," + // 4: beginTime
                "\"END_TIME\" TEXT," + // 5: endTime
                "\"PLAN\" TEXT," + // 6: plan
                "\"SUMMARY\" TEXT," + // 7: summary
                "\"READ_PROGRESS\" INTEGER," + // 8: readProgress
                "\"AUTHOR\" TEXT," + // 9: author
                "\"TAG\" TEXT);"); // 10: tag
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Book entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getBookName());
 
        String addTime = entity.getAddTime();
        if (addTime != null) {
            stmt.bindString(3, addTime);
        }
 
        String introduction = entity.getIntroduction();
        if (introduction != null) {
            stmt.bindString(4, introduction);
        }
 
        String beginTime = entity.getBeginTime();
        if (beginTime != null) {
            stmt.bindString(5, beginTime);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(6, endTime);
        }
 
        String plan = entity.getPlan();
        if (plan != null) {
            stmt.bindString(7, plan);
        }
 
        String summary = entity.getSummary();
        if (summary != null) {
            stmt.bindString(8, summary);
        }
 
        Integer readProgress = entity.getReadProgress();
        if (readProgress != null) {
            stmt.bindLong(9, readProgress);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(10, author);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(11, tag);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Book readEntity(Cursor cursor, int offset) {
        Book entity = new Book( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // bookName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // addTime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // introduction
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // beginTime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // endTime
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // plan
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // summary
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // readProgress
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // author
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // tag
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Book entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBookName(cursor.getString(offset + 1));
        entity.setAddTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIntroduction(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBeginTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEndTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPlan(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSummary(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setReadProgress(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setAuthor(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTag(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Book entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Book entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
