package com.jiahan.action.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BOOK".
 */
public class Book {

    private Long id;
    /** Not-null value. */
    private String bookName;
    private String addTime;
    private String introduction;
    private String beginTime;
    private String endTime;
    private String plan;
    private String summary;
    private Integer readProgress;
    private String author;
    private String tag;

    public Book() {
    }

    public Book(Long id) {
        this.id = id;
    }

    public Book(Long id, String bookName, String addTime, String introduction, String beginTime, String endTime, String plan, String summary, Integer readProgress, String author, String tag) {
        this.id = id;
        this.bookName = bookName;
        this.addTime = addTime;
        this.introduction = introduction;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.plan = plan;
        this.summary = summary;
        this.readProgress = readProgress;
        this.author = author;
        this.tag = tag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBookName() {
        return bookName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public String getAddTime() {
        return addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public String getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getPlan() {
        return plan;
    }

    public void setPlan(String plan) {
        this.plan = plan;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public Integer getReadProgress() {
        return readProgress;
    }

    public void setReadProgress(Integer readProgress) {
        this.readProgress = readProgress;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

}
