package com.jiahan.action.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DOUBT".
 * 小疑惑
 */
public class Doubt {

    private Long id;
    private String question;
    private String answer;
    private String time;
    private Long boo_id;
    private String summary;

    public Doubt() {
    }

    public Doubt(Long id) {
        this.id = id;
    }

    public Doubt(Long id, String question, String answer, String time, Long boo_id, String summary) {
        this.id = id;
        this.question = question;
        this.answer = answer;
        this.time = time;
        this.boo_id = boo_id;
        this.summary = summary;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Long getBoo_id() {
        return boo_id;
    }

    public void setBoo_id(Long boo_id) {
        this.boo_id = boo_id;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

}
