package com.jiahan.action.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DOUBT".
 */
public class Doubt {

    private Long id;
    private String question;
    private String answer;
    private String time;
    private Integer bookId;

    public Doubt() {
    }

    public Doubt(Long id) {
        this.id = id;
    }

    public Doubt(Long id, String question, String answer, String time, Integer bookId) {
        this.id = id;
        this.question = question;
        this.answer = answer;
        this.time = time;
        this.bookId = bookId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getBookId() {
        return bookId;
    }

    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

}
