package com.jiahan.action.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SENTIMENT".
 * 小感悟
 */
public class Sentiment {

    private Long id;
    private String words;
    private String time;
    private Long book_id;

    public Sentiment() {
    }

    public Sentiment(Long id) {
        this.id = id;
    }

    public Sentiment(Long id, String words, String time, Long book_id) {
        this.id = id;
        this.words = words;
        this.time = time;
        this.book_id = book_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWords() {
        return words;
    }

    public void setWords(String words) {
        this.words = words;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Long getBook_id() {
        return book_id;
    }

    public void setBook_id(Long book_id) {
        this.book_id = book_id;
    }

}
