package com.jiahan.action.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SENTIMENT".
 */
public class Sentiment {

    private Long id;
    private String words;
    private String time;
    private Integer booId;

    public Sentiment() {
    }

    public Sentiment(Long id) {
        this.id = id;
    }

    public Sentiment(Long id, String words, String time, Integer booId) {
        this.id = id;
        this.words = words;
        this.time = time;
        this.booId = booId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWords() {
        return words;
    }

    public void setWords(String words) {
        this.words = words;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getBooId() {
        return booId;
    }

    public void setBooId(Integer booId) {
        this.booId = booId;
    }

}
